name: Daily Commit

on:
  schedule:
    - cron: "30 10 * * *"  # Runs daily at 10:30 UTC
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git history access

      - name: Create Commit (22f3002231@ds.study.iitm.ac.in)
        run: |
          echo "Update: $(date)" >> timestamp.log
          git config --global user.email "22f3002231@ds.study.iitm.ac.in"
          git config --global user.name "GitHub Actions"
          git add timestamp.log
          git commit -m "Daily commit: $(date -u)" --allow-empty

      - name: Push changes
        run: git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Critical authorization fix
